### ISSUE TITLE
Userstory #1 - Header

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#1]
## Value statement - a requirement, not a solution
As a user
I need to have a header with the name of the app
so that I know if I'm in the correct app

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/197710337-9419fedf-a702-4dc9-9130-64f7763330d3.png)

## Acceptance criteria
- [x] a header with app name

## Tasks
- [x] fork the react template repository
- [x] clone the react template repository
- [x] create a branch for this userstory
- [x] code the header

## Size
small
