### ISSUE TITLE
userstory #5 - dummy saved flight plans

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#10]
## Value statement - a requirement, not a solution
As a user
I need to have the option to save my just create flight plan
so that I am able to use them in the future

## Description (Text, Scribble, Wireframe, Design)
<img width="493" alt="image" src="https://user-images.githubusercontent.com/112061209/198146279-f6e6ee57-f5fc-429a-9566-4b72f1a556f5.png">

## Acceptance criteria
- [x] save the flight plane
- [x] visualize the saved flight plan in saved flight plans page

## Tasks
- [x] button to save the flight plan in the flight plan page
- [x] code to build fake flight plan with just input data
- [x] save flight plans into local storage

## Size
medium
