### ISSUE TITLE
userstory #7 - Visualize a saved flight plan

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#14]
## Value statement - a requirement, not a solution
As a user 
I need to be able to visualize a saved flight plan
so that I can use it again

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/198587192-879bbf68-aa1f-4c5d-ba16-598dbef570a0.png)

## Acceptance criteria
- [x] when clicking on a saved flight plan I'm able to visualize this flight plan

## Tasks
- [x] change code to App.js
- [x] change code to SavedFlightPlans.js

## Size
small
