### ISSUE TITLE
userstory #9 - Airplane path on map

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#16]
## Value statement - a requirement, not a solution
As a user
I need to see my route into the map
so that I able to check my flight plan

## Description (Text, Scribble, Wireframe, Design)

![Image](https://user-images.githubusercontent.com/112061209/200289544-3395687f-d555-42b0-ac3e-77cfe9b317d0.png)

## Acceptance criteria
- [ ] path draw into the map

## Tasks
- [ ] fetch data from api
- [ ] map style change
- [ ] code to draw over the map

## Size
small

**Comment by jecaps** [comment]
There's not much information about how you would do it (in the Tasks). You can for example create a function that connects each point and so on.
