### ISSUE TITLE
Userstory #2 - Main input fields

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#2]
## Value statement - a requirement, not a solution
As a user 
I need the possibility to input some basic information in my app 
so that it's possible to start the process of creating a flight plan 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/197734711-d9da2429-8ec2-4f57-ae29-637d9bb74bdf.png)

## Acceptance criteria
- [x] input field for the flight number
- [x] input field for the departure airport
- [x] input field for the arrival  airport
- [x] select box for the departure runaway
- [x] select box for the arrival runaway
- [x] date selection field
- [x] hour selection field
- [x] select box for the Aircraft model selection
- [x] input field for the number of passengers
- [x] button to reset the input fields

## Tasks
- [x] create a input field for the flight number
- [x] create a input field for the departure airport
- [x] create a input field for the arrival  airport
- [x] create a dummy select box for the departure runaway
- [x] create a dummy select box for the arrival runaway
- [x] create a date selection field
- [x] create a hour selection field
- [x] create a dummy select box for the Aircraft model selection
- [x] create a input field for the number of passengers
- [x] create a button to reset the input fields

## Size
medium

**Comment by s-kond** [comment]
Do you already do something with the data?

Maybe you can add a submit-button that empties all input-fields, so that a user has the feeling that something is happening already 🤔
