### ISSUE TITLE
userstory #10 - airplane models

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#20]
As a user 
I need to be able to choose between a lot of different airplanes models 
so that I able to use this in the airplane I'm used to. 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/200334772-f46a16bd-6274-43e4-861a-ed29aae4c323.png)

## Acceptance criteria
- [ ] Different airplane models to be displayed on the select box

## Tasks
- [ ] research the most common airplane models
- [ ] add more models of aircraft to the select box. 

## Size
small
