### ISSUE TITLE
userstory #11 Update function to saved flight plans

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#21]
As a user 
I need to update the date and time of my save flight plans 
so that i'm able to update and save the new flight plan. 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/201603329-67740ad3-2823-4300-86e4-90f6882bd54f.png)
## Acceptance criteria
- [ ] update a saved flight plan with new date and time

## Tasks
- [ ] input to update date and time on the flight plan page when data is loaded from saved flight plans. 
- [ ] button to save flight plan.
- [ ] control so that the flight plan is not saved in duplicate and to update the flight plan that's been changed 
- [ ] button to go back to home page. 
- [ ] saved flight plans to show date and time.

## Size
medium
