### ISSUE TITLE
userStory#12 - Restyled from the flight plan page 

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#24]
## Value statement - a requirement, not a solution
As a developer 
I want to see the data oon the flight plan page displayed in a different way 
so that the visualization is better

## Acceptance criteria
- [ ] new organization to show the data

## Tasks
- [ ] restyle the flight plan page
- [ ] divide the information better in the page 

## Size
small
