### ISSUE TITLE
Live flight tracker page userstory #13

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#26]
As a user 
I want the possibility to select some airports 
so that I'm able to see live tracking data of airplanes surrounding the selected airport

## Description (Text, Scribble, Wireframe, Design)
<img width="869" alt="image" src="https://user-images.githubusercontent.com/112061209/202305136-ea08e016-8af9-4015-8d60-a02311febff0.png">

## Acceptance criteria
- [ ] selection an airport from the select box I'm able to get the live information from airplanes on the surrounding of the selected airport 

## Tasks
- [ ] find api for live tracking
- [ ] create a list of airports to be selected from the select box
- [ ] code function to fetch data
- [ ] code maps functions
- [ ] code conditional rendering of different components
- [ ] code popup with plane information
- [ ] styling

## Size
large
