### ISSUE TITLE
final revision of code - userstory#14

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#27]
As a developer 
I need to perform a final revision of code functionality 
so that it can be delivery

## Acceptance criteria
- [ ] Tasks has been fulfilled 

## Tasks
- [ ] restrictions on departure input field
- [ ] restrictions on arrival input field
- [ ] date input field as a required information
- [ ] time input field as a required information
- [ ] aircraft input field as a required information
- [ ] number of passengers as a required information
- [ ] organization of file structure on project tree 

## Size
medium
