### ISSUE TITLE
Component tests - userstory#15

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#29]
## Value statement - a requirement, not a solution
As a developer 
I need to write some test 
so that my app have some elements tested

## Acceptance criteria
- [ ] Pass the tests

## Tasks
- [ ] write test for Runways component
- [ ] write test for Aircraft component
- [ ] write test for AirportSelect component

## Size
small
