### ISSUE TITLE
Userstory #3 - Navigation Bar

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#3]
## Value statement - a requirement, not a solution
As a user
I need to have a navigation bar 
so that I'm able to navigate through the pages of the app

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/197732973-38084b57-a1a6-44de-8a6a-583d5c5ff566.png)

## Acceptance criteria
- [x] fully navigate from page to page of the app

## Tasks
- [x] create a live flights status page and a saved flight plans page
- [x] create the navigation bar
- [x] create a dummy message for the live page and the saved flight plans page

## Size
small
