### ISSUE TITLE
userstory #4 - create flight plan

### ISSUE THREAD

**Issue by kornrumpfl** [kornrumpfl/capstone_flightPlanner#8]
## Value statement - a requirement, not a solution
As a user
I need have a button 
![image](https://user-images.githubusercontent.com/112061209/198046101-5494ab04-2098-4b1d-8cb0-9c6e825a43fa.png) and I also need to be able to return to main page. 
 
so that I am able to see the flight plan I want to create and go back to the main page

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/112061209/198045807-9e02f3e5-5a82-4f9b-a30b-cb87eaf2c59c.png)

## Acceptance criteria
- [x] button on the main page that when clicked takes you to the flight plan page
- [x] a flight plan page that has a dummy text on it a map and a back to home button

## Tasks
- [x] implement the button "Create Flight Plan" on the home page
- [x] implement the Flight Plan page
- [x] insert some dummy text
- [x] insert the map
- [x] implement the go back button
- [x] implement navigation functionality in both buttons

## Size
medium

**Comment by Kheirah** [comment]
LGTM!
